// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVMManagementStore.Repository.Models;

public partial class DealerOrder
{
    public int DealerOrderId { get; set; }

    public int UserId { get; set; }

    public int OrderId { get; set; }

    public int VehicleId { get; set; }

    public int Quantity { get; set; }

    public string Color { get; set; }

    public DateTime? OrderDate { get; set; }

    public string Status { get; set; }

    public string PaymentStatus { get; set; }

    public decimal TotalAmount { get; set; }

    public virtual Order Order { get; set; }

    public virtual User User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}