// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVMManagementStore.Repository.Models;

public partial class Delivery
{
    public int DeliveryId { get; set; }

    public int OrderId { get; set; }

    public int VehicleId { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string DeliveryStatus { get; set; }

    public string Notes { get; set; }

    public virtual Order Order { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}