// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVMManagementStore.Repository.Models;

public partial class Discount
{
    public int DiscountId { get; set; }

    public int UserId { get; set; }

    public string DiscountCode { get; set; }

    public string DiscountName { get; set; }

    public string DiscountType { get; set; }

    public decimal DiscountValue { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public string Status { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}