// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVMManagementStore.Repository.Models;

public partial class Inventory
{
    public int InventoryId { get; set; }

    public int VehicleId { get; set; }

    public int Quantity { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}