// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVMManagementStore.Repository.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int? QuotationId { get; set; }

    public int UserId { get; set; }

    public int VehicleId { get; set; }

    public string Color { get; set; }

    public DateTime? OrderDate { get; set; }

    public string DeliveryAddress { get; set; }

    public string AttachmentImage { get; set; }

    public string AttachmentFile { get; set; }

    public string Status { get; set; }

    public string PromotionCode { get; set; }

    public decimal QuotationPrice { get; set; }

    public decimal FinalPrice { get; set; }

    public virtual ICollection<DealerOrder> DealerOrders { get; set; } = new List<DealerOrder>();

    public virtual ICollection<Delivery> Deliveries { get; set; } = new List<Delivery>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Quotation Quotation { get; set; }

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual ICollection<SalesContract> SalesContracts { get; set; } = new List<SalesContract>();

    public virtual User User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}