// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVMManagementStore.Repository.Models;

public partial class PromotionOption
{
    public int OptionId { get; set; }

    public int PromotionId { get; set; }

    public string OptionName { get; set; }

    public string OptionDescription { get; set; }

    public decimal? OptionValue { get; set; }

    public string OptionType { get; set; }

    public virtual Promotion Promotion { get; set; }
}