// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVMManagementStore.Repository.Models;

public partial class Promotion
{
    public int PromotionId { get; set; }

    public int UserId { get; set; }

    public string PromotionCode { get; set; }

    public int Stock { get; set; }

    public string OptionName { get; set; }

    public decimal? OptionValue { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public virtual User User { get; set; }
}