// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVMManagementStore.Repository.Models;

public partial class Quotation
{
    public int QuotationId { get; set; }

    public int UserId { get; set; }

    public int VehicleId { get; set; }

    public DateTime? QuotationDate { get; set; }

    public decimal BasePrice { get; set; }

    public decimal FinalPrice { get; set; }

    public string AttachmentImage { get; set; }

    public string AttachmentFile { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual User User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}