// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVMManagementStore.Repository.Models;

public partial class Report
{
    public int ReportId { get; set; }

    public int? UserId { get; set; }

    public int? OrderId { get; set; }

    public string ReportType { get; set; }

    public DateOnly? CreatedDate { get; set; }

    public DateOnly? ResolvedDate { get; set; }

    public string Content { get; set; }

    public string Status { get; set; }

    public virtual Order Order { get; set; }

    public virtual User User { get; set; }
}