// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVMManagementStore.Repository.Models;

public partial class SalesContract
{
    public int SalesContractId { get; set; }

    public int OrderId { get; set; }

    public DateTime? ContractDate { get; set; }

    public string Terms { get; set; }

    public string SignedByDealer { get; set; }

    public virtual Order Order { get; set; }
}