// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVMManagementStore.Repository.Models;

public partial class Vehicle
{
    public int VehicleId { get; set; }

    public string Type { get; set; }

    public string Model { get; set; }

    public string Version { get; set; }

    public string Distance { get; set; }

    public string Timecharging { get; set; }

    public string Speed { get; set; }

    public string Image1 { get; set; }

    public string Image2 { get; set; }

    public string Image3 { get; set; }

    public string Color { get; set; }

    public decimal Price { get; set; }

    public string Status { get; set; }

    public virtual ICollection<DealerOrder> DealerOrders { get; set; } = new List<DealerOrder>();

    public virtual ICollection<Delivery> Deliveries { get; set; } = new List<Delivery>();

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Quotation> Quotations { get; set; } = new List<Quotation>();

    public virtual ICollection<TestDriveAppointment> TestDriveAppointments { get; set; } = new List<TestDriveAppointment>();
}